### ISSUE TITLE
When screen shot of this taken on andriod mobile and scanned from gpay it is not working

### ISSUE THREAD

**Issue by eshopblr** [cyberboysumanjay/upayi#4] opened 2021-11-03 20:01 UTC
With following sequence it is not working 

1. Take a screen shot of the QR code generated on mobile 
2. open google GPAY 
3. choose scan from image
4. This is giving error and not scanning. Gives error not able to scan for upi code from uploaded image

**Comment by info-lamin** [comment] 2021-11-21 13:49
Crop the image, so that it has only the qr code
Then it will work.
The problem is on gpay's side only.

**Comment by cyberboysumanjay** [comment] 2023-07-26 17:40
Also note that by scanning the QR from gallery there is a limit of 2k per transaction.

**Comment by cyberboysumanjay** [comment] 2023-07-26 17:41
Closed this issue for now, if you are facing similar issue then feel free to open.

**Closed as completed by cyberboysumanjay** 2023-07-26 17:40 UTC
